# docker-compose.yml
version: "3"

services:
    mysql:
        image: mysql:5.7
        volumes:
            - db_volume:/var/lib/mysql
        environment:
            MYSQL_DATABASE: my-services
            MYSQL_USER: 
            MYSQL_PASSWORD: 
            MYSQL_ROOT_PASSWORD: 

volumes:
    db_volume:
